.ts    10:1    error    This line has a length of 110. Maximum allowed is 80          max-len    66:17   warning  Unexpected any. Specify a different type                      @typescript-eslint/no-explicit-any    67:1    error    This line has a length of 90. Maximum allowed is 80           max-len    69:1    error    This line has a length of 87. Maximum allowed is 80           max-len    80:1    error    This line has a length of 106. Maximum allowed is 80          max-len   105:3    error    Do not use "@ts-ignore" because it alters compilation errors  @typescript-eslint/ban-ts-comment   111:1    error    This line has a length of 109. Maximum allowed is 80          max-len   123:1    error    This line has a length of 117. Maximum allowed is 80          max-len   126:28   warning  Unexpected any. Specify a different type                      @typescript-eslint/no-explicit-any   128:1    error    This line has a length of 168. Maximum allowed is 80          max-len   137:1    error    This line has a length of 81. Maximum allowed is 80           max-len   138:1    error    This line has a length of 104. Maximum allowed is 80          max-len   141:1    error    This line has a length of 85. Maximum allowed is 80           max-len   155:1    error    This line has a length of 113. Maximum allowed is 80          max-len   164:17   warning  Unexpected any. Specify a different type                      @typescript-eslint/no-explicit-any   165:1    error    This line has a length of 93. Maximum allowed is 80           max-len   166:1    error    Expected indentation of 6 spaces but found 8                  indent   167:1    error    Expected indentation of 6 spaces but found 8                  indent   168:1    error    Expected indentation of 6 spaces but found 8                  indent   169:1    error    Expected indentation of 6 spaces but found 8                  indent   170:1    error    Expected indentation of 4 spaces but found 6                  indent   172:1    error    This line has a length of 81. Maximum allowed is 80           max-len   173:9    error    'httpStatusCode' is never reassigned. Use 'const' instead     prefer-const   176:1    error    This line has a length of 170. Maximum allowed is 80          max-len   176:147  error    Strings must use doublequote                                  quotes   177:1    error    This line has a length of 89. Maximum allowed is 80           max-len   185:45   error    Strings must use doublequote                                  quotes   191:1    error    Trailing spaces not allowed                                   no-trailing-spaces   195:48   error    Missing trailing comma                                        comma-dangle
/home/user/studio/functions/src/paypalClient.ts
  10:1   error  This line has a length of 92. Maximum allowed is 80   max-len
  12:1   error  This line has a length of 93. Maximum allowed is 80   max-len
  15:1   error  This line has a length of 101. Maximum allowed is 80  max-len
  18:1   error  This line has a length of 97. Maximum allowed is 80   max-len
  20:55  error  Block must not be padded by blank lines               padded-blocks
  29:1   error  This line has a length of 96. Maximum allowed is 80   max-len
  30:1   error  This line has a length of 82. Maximum allowed is 80   max-len

✖ 36 problems (33 errors, 3 warnings)
  11 errors and 0 warnings potentially fixable with the `--fix` option.

Error: functions predeploy error: Command terminated with non-zero exit code 1