> lint > eslint --ext .js,.ts .
/home/user/studio/functions/src/index.ts
  10:9   warning  'onRequest' is defined but never used  @typescript-eslint/no-unused-vars
  11:13  warning  'logger' is defined but never used     @typescript-eslint/no-unused-vars

✖ 2 problems (0 errors, 2 warnings)

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

src/index.ts:10:1 - error TS6133: 'onRequest' is declared but its value is never read.

10 import {onRequest} from "firebase-functions/v2/https";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:11:1 - error TS6133: 'logger' is declared but its value is never read.

11 import * as logger from "firebase-functions/logger";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 errors in the same file, starting at: src/index.ts:10

Error: functions predeploy error: Command terminated with non-zero exit code 2
studio-4948799546:~/studio{master}$ firebase deploy --only functions

=== Deploying to 'autonest-vn4w5'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

✔  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy
Serving at port 8727

i  extensions: ensuring required API firebaseextensions.googleapis.com is enabled...
✔  extensions: required API firebaseextensions.googleapis.com is enabled
i  functions: Loaded environment variables from .env.
i  functions: preparing functions directory for uploading...
i  functions: packaged /home/user/studio/functions (92.84 KB) for uploading
i  functions: ensuring required API run.googleapis.com is enabled...
i  functions: ensuring required API eventarc.googleapis.com is enabled...
i  functions: ensuring required API pubsub.googleapis.com is enabled...
i  functions: ensuring required API storage.googleapis.com is enabled...
✔  functions: required API pubsub.googleapis.com is enabled
✔  functions: required API run.googleapis.com is enabled
✔  functions: required API storage.googleapis.com is enabled
⚠  functions: missing required API eventarc.googleapis.com. Enabling now...
✔  functions: required API eventarc.googleapis.com is enabled
i  functions: generating the service identity for pubsub.googleapis.com...
i  functions: generating the service identity for eventarc.googleapis.com...
✔  functions: functions folder uploaded successfully
i  functions: creating Node.js 22 (2nd Gen) function helloWorld(us-central1)...
i  functions: creating Node.js 22 (2nd Gen) function paypalAPI(us-central1)...
✔  functions[helloWorld(us-central1)] Successful create operation.
✔  functions[paypalAPI(us-central1)] Successful create operation.
Function URL (helloWorld(us-central1)): https://us-central1-autonest-vn4w5.cloudfunctions.net/helloWorld
Function URL (paypalAPI(us-central1)): https://us-central1-autonest-vn4w5.cloudfunctions.net/paypalAPI
⚠  functions: No cleanup policy detected for repositories in us-central1. This may result in a small monthly bill as container images accumulate over time.
✔ How many days do you want to keep container images before they're deleted? 1
i  functions: Configuring cleanup policy for repository in us-central1. Images older than 1 days will be automatically deleted.
i  functions: Configured cleanup policy for repository in us-central1.

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/autonest-vn4w5/overview