studio-4948799546:~/studio{master}$ cd functions studio-4948799546:~/studio/functions{master}$ rm -rf node_modules package-lock.json studio-4948799546:~/studio/functions{master}$ npm install --force npm warn using --force Recommended protections disabled. npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful. npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
added 659 packages, and audited 660 packages in 1m

145 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
studio-4948799546:~/studio/functions{master}$ cd ..
studio-4948799546:~/studio{master}$ firebase deploy --only functions

=== Deploying to 'autonest-vn4w5'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

/home/user/studio/functions/src/index.ts
   25:27  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
   93:17  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any
  147:25  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any
  170:17  warning  Unexpected any. Specify a different type        @typescript-eslint/no-explicit-any

/home/user/studio/functions/src/paypalClient.ts
  6:16  error  Require statement not part of import statement  @typescript-eslint/no-var-requires

✖ 5 problems (2 errors, 3 warnings)

Error: functions predeploy error: Command terminated with non-zero exit code 1
studio-4948799546:~/studio{master}$