.ts    78:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any   129:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any   151:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
✖ 3 problems (0 errors, 3 warnings)

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

✔  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy
Serving at port 8209

Error: Cannot find module '@paypal/checkout-server-sdk'
Require stack:
- /home/user/studio/functions/lib/paypalClient.js
- /home/user/studio/functions/lib/index.js
- /home/user/studio/functions/node_modules/firebase-functions/lib/runtime/loader.js
- /home/user/studio/functions/node_modules/firebase-functions/lib/bin/firebase-functions.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at Object.<anonymous> (/home/user/studio/functions/lib/paypalClient.js:30:47)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Module.require (node:internal/modules/cjs/loader:1298:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/studio/functions/lib/paypalClient.js',
    '/home/user/studio/functions/lib/index.js',
    '/home/user/studio/functions/node_modules/firebase-functions/lib/runtime/loader.js',
    '/home/user/studio/functions/node_modules/firebase-functions/lib/bin/firebase-functions.js'
  ]
}

Error: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error