studio-4948799546:~/studio{master}$ cd functions/ studio-4948799546:~/studio/functions{master}$ npm install --force npm warn using --force Recommended protections disabled. npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful. npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
added 659 packages, and audited 660 packages in 1m

145 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
studio-4948799546:~/studio/functions{master}$ npm run build

> build
> tsc

studio-4948799546:~/studio/functions{master}$ cd ..
studio-4948799546:~/studio{master}$ firebase deploy --only functions

=== Deploying to 'autonest-vn4w5'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

/home/user/studio/functions/src/index.ts
   78:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  129:25  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  151:17  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 3 problems (0 errors, 3 warnings)

Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

✔  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: Loading and analyzing source code for codebase default to determine what to deploy
Serving at port 8359

Error: Cannot find module '@paypal/checkout-server-sdk'
Require stack:
- /home/user/studio/functions/lib/paypalClient.js
- /home/user/studio/functions/lib/index.js
- /home/user/studio/functions/node_modules/firebase-functions/lib/runtime/loader.js
- /home/user/studio/functions/node_modules/firebase-functions/lib/bin/firebase-functions.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1212:15)
    at Module._load (node:internal/modules/cjs/loader:1043:27)
    at Module.require (node:internal/modules/cjs/loader:1298:19)
    at require (node:internal/modules/helpers:182:18)
    at Object.<anonymous> (/home/user/studio/functions/lib/paypalClient.js:31:29)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Module.require (node:internal/modules/cjs/loader:1298:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/studio/functions/lib/paypalClient.js',
    '/home/user/studio/functions/lib/index.js',
    '/home/user/studio/functions/node_modules/firebase-functions/lib/runtime/loader.js',
    '/home/user/studio/functions/node_modules/firebase-functions/lib/bin/firebase-functions.js'
  ]
}

Error: Functions codebase could not be analyzed successfully. It may have a syntax or runtime error