studio-4948799546:~/studio{master}$ firebase deploy --only functions
=== Deploying to 'autonest-vn4w5'...

i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

/home/user/studio/functions/src/index.ts
   70:17  warning  Unexpected any. Specify a different type                      @typescript-eslint/no-explicit-any
   98:3   error    Do not use "@ts-ignore" because it alters compilation errors  @typescript-eslint/ban-ts-comment
  121:1   error    This line has a length of 91. Maximum allowed is 80           max-len
  127:25  warning  Unexpected any. Specify a different type                      @typescript-eslint/no-explicit-any
  129:1   error    This line has a length of 107. Maximum allowed is 80          max-len
  132:1   error    This line has a length of 95. Maximum allowed is 80           max-len
  134:1   error    This line has a length of 90. Maximum allowed is 80           max-len
  141:1   error    This line has a length of 90. Maximum allowed is 80           max-len
  148:17  warning  Unexpected any. Specify a different type                      @typescript-eslint/no-explicit-any
  159:1   error    This line has a length of 94. Maximum allowed is 80           max-len
  182:1   error    This line has a length of 94. Maximum allowed is 80           max-len

/home/user/studio/functions/src/paypalClient.ts
   5:1  error  This line has a length of 90. Maximum allowed is 80  max-len
  12:1  error  This line has a length of 86. Maximum allowed is 80  max-len
  13:1  error  This line has a length of 98. Maximum allowed is 80  max-len
  14:1  error  This line has a length of 99. Maximum allowed is 80  max-len
  25:1  error  This line has a length of 87. Maximum allowed is 80  max-len

✖ 16 problems (13 errors, 3 warnings)

Error: functions predeploy error: Command terminated with non-zero exit code 1